name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ Decorating_my_profile }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Kim Hyo Chan
          git config user.email skkhc0317@gmail.com
          git remote set-url origin https://github.com/HyoChan1117/HyoChan1117.git
          git add -A .
          git commit -m "generated"
          git push https://$GITHUB_TOKEN@github.com/HyoChan1117/HyoChan1117.git
